import React, { Component } from 'react';
import { Link } from 'react-router-dom';

import './Landing.css';

class Landing extends Component {
  state = {
    email: '',
    password: ''
  };

  handleInputChange = event => {
    const { name, value } = event.target;
    this.setState({
      [name]: value
    });
  };

  handleFormSubmit = event => {
    event.preventDefault();
    if (this.state.email && this.state.password) {
      //do so sort of get from DB and verification
    }
  };

  render() {
    return (
      <div className="bg-img">
        <div className="container">
          <br />
          <br />
          <div className="row">
            <div className="col-sm-4 offset-sm-4">
              <div className="card text-center" id="sign-up">
                <h3>
                  <Link to="/signup" id="link-text">
                    Sign Up/Log In
                  </Link>
                </h3>
              </div>
            </div>
          </div>
          <br />
          <br />
          <div className="row">
            <div className="col-sm-8 offset-sm-2">
              <div className="card" id="log-in">
                <div className="card-body text-center" id="info-text">
                  <h3>Welcome to Bill Buster</h3>
                  <p>
                    Bill Buster is a mobile friendly app that allows users to
                    log in to their virtual filing system. Users can input their
                    billing information for any type that they may have, add and
                    store picture copies of their statements, and get a quick
                    look at the spread of their finances from the pie chart
                    generated by their input data. Users must log in to be able
                    to view their information. All routes beyond the landing
                    page are protected. Bill Buster is designed to make managing
                    your finances simpler and more comprehensive, without all
                    the clutter.
                  </p>
                  {/* <form>
                    <div className="form-group">
                      <label>Username or email</label>
                      <input
                        type="text"
                        className="form-control"
                        name="email"
                      />
                    </div>
                      <label>Password</label>
                      <input
                        type="password"
                        className="form-control"
                        name="password"
                      />
                    </div>
                    <button className="btn-warning btn-lg" type="submit">
                      Log In
                    </button>
                  </form> */}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }
}

export default Landing;
